### ISSUE TITLE
Demo Incomplete

### ISSUE THREAD

**Issue by p-danielrpg** [HashakGik/BulletHell-RMMV#4]
When I try to launch the demo (not the one from the link) i get "Failed to load: js/plugins/BulletHell.js" error. 
I couldn't find the BulletHell.js in any folder.

**Comment by HashakGik** [comment]
Hi!

The BulletHell.js is generated from the Makefile (and the demo is consequently updated, this saves **a lot** of time when changing things, instead of copypasting many things every time).
If you are not familiar with Makefiles, I suggest you to download one of the [stable releases](https://github.com/HashakGik/BulletHell-RMMV/releases).

Thank you for the issue.

EDIT: I see this is your first issue and you are moving your first steps here on GitHub! Welcome!
If you need help with anything here, feel free to ask!

**Comment by HashakGik** [comment]
Commit d9b5b3b fixed this issue. Closing.
